name: Build and test

on:
  push:
    branches:
      - 2.x
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@master
        with:
          path: build/libs/*.jar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptDev/skript-test-action@v1.4
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: dev/update
          extra_plugins_directory: extra-plugins/
